### ISSUE TITLE
Why did you remove Wutu?

### ISSUE THREAD

**Issue by kodiadon** [Ezra-Hubbard/Ezra-Hubbard.github.io#11]
I saw this in your repo and installed it yesterday.  It seems to work fine. I'm having no problems with it.  It resembles kingpin (renamed Venom).

**Comment by Ezra-Hubbard** [comment]
Um, well glad it is working for you, but for me, and also with other testers nothing is scraping. 

Scraper dialog does not appear and bugs in error log. Working on fixing it. 

What version of Ezscrapers are you on? I am trying to work out if I broke something in Wutu or broke something in the scrapers

**Comment by kodiadon** [comment]
I am using the latest version.  I think I had an update for Ezscrapers, which I installed that 1st,  then I decided to try Wutu so I downloaded that and linked it to My accounts.

**Comment by Ezra-Hubbard** [comment]
hmmm, well why is it working for you and not for me or anyone else lol

**Comment by kodiadon** [comment]
Hang on. Let me try it now

**Comment by kodiadon** [comment]
I have My Accounts 2.0.5d, Ezra Scrapers Module 0.0.10,  Ezra 0.1.5b, Wutu 0.0.1a, kingpin 0.0.14.

Strange, when I tried it yesterday it was working.  NOW it won't scrape

**Comment by Ezra-Hubbard** [comment]
> 

Yeh, same problem i ran into . One minute working. then next day, everything broken lol

working on it, rebuilding it from scratch to figure out where things went pear shaped

**Comment by kodiadon** [comment]
It looks like it'll be a great addon...once the bugs get worked out

**Comment by kodiadon** [comment]
I still see Wutu in your repo

**Comment by Ezra-Hubbard** [comment]
it should vanish with next refresh or, a fixed version appear.

I think I have found the issue. After 24 hours of trawling through python (and my python knowledge is like 2/100), whereas my xml/po knowledge which is my main coding thing is like 75/100) and the issue, appears to be have been a last minute tiny edit i made to the frigging language files.....

**Comment by Ezra-Hubbard** [comment]
ok, a new copy has been pushed 0.0.3

This on a basic level should work. May or may not need a trakt reauth, and will probably need tools > trakt tools > force full db thingy

Honestly, the better option at the moment is Kingpin. This is not going to get a lot of love and attention. Its just going to be got to a point where it works with ezscrapers and accounts

**Comment by Arthur1967** [comment]
I just installed Wutu and it's working fine but I had to install the context menu and the plug-in video and then my account separately

**Comment by kodiadon** [comment]
After I saw Wutu wasn't working, I deleted Wutu and everything related to it.  Now, with the new Wutu, I CAN NOT get it to install. Last night after I came home I saw there was an updater to the scrapers, so I installed that. Then  I tried to install Wutu. It 1st starts to download but never completes and I see "Installation Failed" . I've tried more than 6 times and always fails.

**Comment by Arthur1967** [comment]
Forgot you have to install ez scrapers module to

**Comment by Ezra-Hubbard** [comment]
should now install without issue.

for some reason the git was trying to install version 0.0.1a which doesnt exist. no idea what that was, but did a repo rebuild and its all playing nicely now. 

well, as far as installation goes :')

**Comment by kodiadon** [comment]
Yes I just installed it without problems. Thank you

**Comment by Arthur1967** [comment]
Thank you
