### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Arthur1967** [Ezra-Hubbard/Ezra-Hubbard.github.io#13]
Posting this here because I don't know where else you would read it if Wutu And Ezra use the same scrapers is there any sense of having both add ons Thank you for your commitment looking forward to seeing what else you come up with have a good day

**Comment by Ezra-Hubbard** [comment]
Not really.

Ezra will get all the love from me as that is my daily driver.

Wutu was only really put out because a few people requested a venom fork that supported the ezra scraper package.

There are other venom forks, notably Kingpin and Umbrella which will get more love.
