### ISSUE TITLE
Scaper help

### ISSUE THREAD

**Issue by Arthur1967** [Ezra-Hubbard/Ezra-Hubbard.github.io#17]
Which scraper would I turn on to get streams from jive It gets all of my current shows only in standard definition by the picture quality is very clear thank you I see it in another add-on I have But it doesn't show the scraper thank you I'm way out of my league

**Comment by dm2912** [comment]
what is jive?

**Comment by Arthur1967** [comment]
It's kind of what I was hoping you would know I used the add-on release bb A lot of the streams come from JIVE tV shows from oxygen but it doesn't tell you what scraper it uses so I was hoping you would know so I could turn that scraper on and that is used with real debrid might be a hoster I don't know And I can't find anything on Google about it it's a standard stream I know that

**Comment by Arthur1967** [comment]
Very clear picture for standard definition

**Comment by Arthur1967** [comment]
Says web~dl x264~JiVE

**Comment by Arthur1967** [comment]
I'll close it for now but boy does it pick up a lot of current shows thank you

**Comment by Ezra-Hubbard** [comment]
probably the name of the ripping person/group

**Comment by Arthur1967** [comment]
OK I see because it gets dateline and a few others that I can't get in any
other add-ons thank you it probably is the name of the person
