### ISSUE TITLE
Ezra (and/or Kingpin) seem to have issues with Trakt/My Accounts module

### ISSUE THREAD

**Issue by Madddcow** [Ezra-Hubbard/Ezra-Hubbard.github.io#19]
I have both Ezra and Kingpin installed on my Nvidia Shield 2019 (in addition to Seren, The Crew and a few other addons) and authenticating Ezra with Trakt always results in Kingin (and vice versa) requiring re-authenticating within 24 hours or so.  This happens constantly i.e. re-authenticating either Ezra or Kingpin always causes issues for the other.

Given that Ezra constantly seem to be problematic with Trakt, perhaps the issue is with Ezra?

What additional info can I provide? I'm not sure that a log is going to show why either addon constantly require re-authenticating but I'm happy to provide one if requred.

**Comment by Madddcow** [comment]
Two other users running both Ezra and Kingpin have just confirmed on Reddit that they're experiencing the same thing....so I'm glad it's not just me.

There definitely seems to be an issue here with either Ezra, Kingpin, My Accounts are some combination of these.

**Comment by dm2912** [comment]
in on the kingpin (venom clones in general) side

Fixes were pushed to Umbrella earlier and to Wutu shortly. Hopefully Kingpin will merge them later.

FWIW.. Wutu is going to be killed off as its not really needed.

**Comment by Ezra-Hubbard** [comment]
it looks like its an issue with venom clones in that theres no trakt expiry. 

This should be fixed in umbrella and hopefully the fix will be patched to kingpin as well

(its been patched to Wutu but wutu is largely redundant as Umbrella is getting very regular updates and kingpin also)
