### ISSUE TITLE
Next up dialogue box is full screen 

### ISSUE THREAD

**Issue by Bhav1111** [Ezra-Hubbard/Ezra-Hubbard.github.io#23]
Next up dialogue box is not in corner but stretched full screen. Buttons show up on bottom right.

**Comment by Ezra-Hubbard** [comment]
Duplicate of https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/issues/22

Fixed in https://github.com/Ezra-Hubbard/Ezra-Hubbard.github.io/commit/d84ea1c039b46ec901a0f5694909413e4a4e2ca3~

Use Issue 22 if it continues to be a problem. :D

Sorry about that
