### ISSUE TITLE
[Bug] Ezra Cam Filter

### ISSUE THREAD

**Issue by AltFreq07** [Ezra-Hubbard/Ezra-Hubbard.github.io#26]
Unfortunalty it appears that HQCAM can bypass the cam filter. Should just be a case of adding it to the filter [here ](https://github.com/Ezra-Hubbard/plugin.video.ezra/blob/eb516969067b64f44ac62adab858fb9890e0aab4/resources/lib/modules/source_utils.py#L17)

I can make a pull request if required

![image](https://user-images.githubusercontent.com/36876748/179448738-808d1ff6-1c1e-4ae7-9ef6-f26ebbfbe884.png)

**Comment by Ezra-Hubbard** [comment]
will add, should be straightforward as you say

**Comment by umbrellaplug** [comment]
Nice find! Will add as well.

**Comment by umbrellaplug** [comment]
Hmm somehow I already had this and more.
@Ezra-Hubbard  You show:
`CAM = ('.cam.', 'camrip', 'hdcam', '.hd.cam', 'cam.rip', 'dvdcam')`

In my scrapers module I show:
CAM = ('1xbet', 'betwin', '.cam.', 'camrip', 'cam.rip', 'dvdcam', 'dvd.cam', 'dvdts', 'hdcam', '.hd.cam', '.hctc', '.hc.tc', '.hdtc',
				'.hd.tc', 'hdts', '.hd.ts', 'hqcam', '.hg.cam', '.ts.', '.tc.', 'tsrip', 'telecine', 'telesync', 'tele.sync')

**Comment by kodifitzwell** [comment]
scrapers `source_utils.py` CAM tags it for quality and not in UNDESIRABLES.

addon `source_utils.py` CAM tags it for quality and if the setting is correct, is filtered in `sources.py`:

    def _quality_filter(self):
        setting = 'results_quality_%s' % self.media_type if not self.autoplay else 'autoplay_quality_%s' % self.media_type
        filter_list = quality_filter(setting)
        if self.include_prerelease_results and 'SD' in filter_list: filter_list += ['SCR', 'CAM', 'TELE']
        return filter_list

**Comment by Ezra-Hubbard** [comment]
done in 0.2.5
