### ISSUE TITLE
Trakt collection 

### ISSUE THREAD

**Issue by zois1** [Ezra-Hubbard/Ezra-Hubbard.github.io#28]
we can no longer remove series from traktlist collection

**Comment by Ezra-Hubbard** [comment]
working for me.

Hit ontext menu on show

Trakt list Manager

Remove from Trakt List

and then select collection

just tested on two shows and both worked fine :S

**Comment by zois1** [comment]
> working for me.
> 
> Hit ontext menu on show
> 
> Trakt list Manager
> 
> Remove from Trakt List
> 
> and then select collection
> 
> just tested on two shows and both worked fine :S

thanks for your reply, cleaned cache and it works for me again.
