### ISSUE TITLE
Feature Request - Add Source Filtering option based on Size limit

### ISSUE THREAD

**Issue by sathish804** [Ezra-Hubbard/Ezra-Hubbard.github.io#29]
Dear Dev,

Please add the Source filtering options based on the Size limit for movies and tv-shows instead of the Internet speed setting.

Thanks and Regards,
Sathish.

**Comment by Ezra-Hubbard** [comment]
It's not going to happen I'm afraid. 

1) its beyond my python ability right now, as someone who hadnt even touched python at all till a month ago.

But mainly

2) there's a reason why setting by speed is better. Size doesnt make any account for length. a 5gb tv episode of 30 minutes is not the same quality as a 5gb tv episode of 60 minutes, just as a 20gb movie of 90 minutes is not the same as a 20gb movie of 3 hours. 

The bandwidth options means it will give you the optimum quality for your connection regardless of how long the episode/movie is. 

So for a 30 minute episode it may cap out at 4gb, but for a 60 minute episode it may cap out at 8gb, and for a 2 hour movie, it may cap out at 16gb
