### ISSUE TITLE
Tmdb api key

### ISSUE THREAD

**Issue by Arthur1967** [Ezra-Hubbard/Ezra-Hubbard.github.io#30]
I filled out the information for Api key it shows it but always comes up empty and there is no log error to send to you When I go to the website my list is built and my watchlist is there

**Comment by Ezra-Hubbard** [comment]
tmdb watchlists? ive not experimented iwth those at all. will have a look

**Comment by Arthur1967** [comment]
OK because it works in the umbrella and you both use my account so I'm not quite sure why it's not working with yours I like your hat on that's why I just wanted to know
